# Generated by Django 4.0.4 on 2022-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_authors_author_rename_books_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books.book'),
        ),
        migrations.AddField(
            model_name='genre',
            name='books',
            field=models.ManyToManyField(related_name='genres', to='books.book'),
        ),
    ]
